# **Numpy**

Numpy is an open source numerical library used for working with mathematical functions with multi-dimensional array and matrix data structures. It is already installed in our environment and is very common in Data Science and Machine Learning.

**Why use Numpys?** Numpy arrays use less memory than normal python list. A normal python list is a group of pointers to separate Python objects. A numpy array is designed to be an array of uniform values without using space for type pointers. Numpys can also read information faster than normal python and has lots of convenient broadcasting operations that can be performed across array dimensions.

Topic: Creating Arrays.

*   Converting existing objects to array
*   Using numpy functions to generate arrays
*   Creating arrays and matrices of random values
*   Basic array attributes.



In [ ]:
import numpy as np

In [ ]:
myList = [1, 2, 3]

In [ ]:
np.array(myList)

array([1, 2, 3])

In [ ]:
nested_list = [[1,2], [3,4], [5,6]]

In [ ]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Get 0-9
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Get even numbers
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# returns 3 zeros of type floating point
np.zeros(3)

array([0., 0., 0.])

In [ ]:
# returns 4x4 matrix of 0s
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# returns 4x10 matrix of 10s
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# returns a 4x4 matric of 1s
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# returns 3 evenly spaced numbers(0, 5, 10)
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [ ]:
# returns 20 evenly spaced numbers
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
# returns a 5x5 matrix with 1s arranged in a diagonal
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# returns 2 number random from 0 to 1
np.random.rand(2)

array([0.5337313 , 0.98263387])

In [ ]:
# returns a 3x4 matrix of random numbers from 0 to 1
np.random.rand(3, 4)

array([[0.13798772, 0.61905615, 0.76888912, 0.98783183],
       [0.29494792, 0.36780839, 0.62689853, 0.86176113],
       [0.74686255, 0.60535052, 0.28991008, 0.66769376]])

In [ ]:
# returns a 5x5 matrix of random numbers from a standard distribution where the mean is 0 and the variance is 1
np.random.randn(5,5)

array([[-1.74249128, -1.24491831,  2.02908727,  0.46791539, -0.67257183],
       [ 0.48104401, -0.0137386 , -0.59940423, -1.15247487,  1.426762  ],
       [ 1.54234977,  0.12071245,  0.15064896,  1.04251357,  1.26218613],
       [-0.12022364, -0.14440909,  1.00847839,  0.47670153, -0.53235504],
       [ 0.26390073,  0.51717203, -0.9261499 , -0.83742994,  0.44727904]])

In [ ]:
# return a random number between 1 and 100
np.random.randint(1, 100)

14

In [ ]:
# returns 10 random numbers between 1 and 100
np.random.randint(1, 100, 10)

array([99, 56, 64, 85, 74, 25, 86, 91, 31, 30])

In [ ]:
# returns 2x3 matrix of random numbers between 1 and 100
np.random.randint(1, 100, (2,3))

array([[16, 54, 85],
       [66, 79, 17]])

In [ ]:
# seed allows of the replication mof random values on different environments / devices
# seed only applies to the next random generation
np.random.seed(42)
np.random.rand(4)


array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(0, 50, 10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [ ]:
# before reshape, the arr shape is (25,)
arr.shape

(25,)

In [ ]:
# after reshape, the arr shape is now (5,5)
# assign to arr to change the original array
arr = arr.reshape(5, 5)

In [ ]:
# arr shape is now (5,5)
arr.shape

(5, 5)

In [ ]:
# This returns an error because arr has 25 elements and 3x6 only has space for 18 elements.
arr.reshape(3,6)

ValueError: ignored

In [ ]:
# returns the highest value in the array
ranarr.max();

In [ ]:
# returns the index of the highest value
ranarr.argmax();

In [ ]:
# returns the lowest value in the array
ranarr.min();

In [ ]:
# returns the index of the highest value
ranarr.argmin();

In [ ]:
# returns the data type of the array
ranarr.dtype

dtype('int64')

In [ ]:
myarr = np.random.rand(4)

In [ ]:
myarr

array([0.02058449, 0.96990985, 0.83244264, 0.21233911])

In [ ]:
myarr.dtype

dtype('float64')