# Numpy Indexing and Selection

Indexing and Selection
*   Grabbing single element
*   Grabbing a slice of of elements
*   Broadcasting selections
*   Indexing and selection in 2-dimensions
*   Conditional selection



In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0, 11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# select element in index 8
arr[8]

8

In [ ]:
# selects element from index 1 to 4 (up to but not including 5)
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
# selects elements from index 0 to 4
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
# select elements from index 0 to 4
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
# selects elements from index 5 onwards
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# unlike lists, numpys have the ability to broadcast
# change the value of index 0 to 4 to 100 - we can't do this with list!
# in list, we must use the same shape and size to reassign it's value
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
slice_of_arr = arr[0:5]

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# change all elements in array to 99
# also effects the original arr!
slice_of_arr[:] = 99

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
# to not edit the original array, we must copy it
arr_copy = arr.copy();

In [ ]:
arr_copy[:] = 100

In [ ]:
# 2d array
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# get number of rows and cols
arr_2d.shape

(3, 3)

In [ ]:
# returns first row
arr_2d[0]

array([ 5, 10, 15])

In [ ]:
# returns second row
arr_2d[1]

array([20, 25, 30])

In [ ]:
# returns element at row 1 index 1
# longer alternative
# arr_2d[1][1]
arr_2d[1, 1]

25

In [ ]:
# slicing 2d array
# returns row 0 and 1 and elements at index 1 and beyond
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# checks if elements are greater than 4
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
# returns an array containings the elements that are greater than 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# returns an array containings the elements that are greater than 4
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
test_arr = np.arange(1,4)

In [ ]:
test_arr[[True, True, True]]

array([1, 2, 3])