In [2]:
import numpy as np

In [5]:
arr = np.arange(0,10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# add 5 to every element
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
# subtract 2 from every element
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [8]:
# add elements from 2 arrays
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# subtract elements from 2 arrays
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# divide elements from 2 arrays
# dividing by 0 in numpy only returns a warning
arr / arr

<ipython-input-12-0a06dfdf2d70>:3: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
# dividing by 0 in python throws an error
1 / 0

ZeroDivisionError: ignored

In [15]:
# dividing by 0 in numpy only returns a warning
1/arr

<ipython-input-15-22115141b14c>:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [16]:
# squareroot of every element in the array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [17]:
# (trigonometric fn) sin of every element in the array
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [18]:
# logarithmic of every element in the array
np.log(arr)

<ipython-input-18-640ebec45dc4>:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [19]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# takes the sum of all elements in the array
arr.sum()

45

In [23]:
# takes the mean of all elements in the array
arr.mean()

4.5

In [24]:
# returns the highest element in the array
arr.max()

9

In [29]:
# returns the variance
arr.var()

8.25

In [28]:
# returns the standard deviation
arr.std()

2.8722813232690143

In [33]:
# 2d 5x5 array
arr2d = np.arange(0, 25).reshape(5,5)

In [34]:
arr2d.shape

(5, 5)

In [35]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
# returns sum of all elements in the array (rows and cols)
arr2d.sum()

300

In [40]:
# axis=0 : performs the sum operation across the rows and gets the sum per columns
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [39]:
# axis=1: performs the sum operation across the columns and gets the sum the rows
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])